FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install -r requirements.txt

# Instala watchdog
RUN pip install watchdog

# Copia el contenido del directorio actual en /app
COPY . .

# Expone el puerto 8000 para la aplicación
EXPOSE 8000


