version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    links:
      - db_mongo
    volumes:
      - .:/app
    command: >
      watchmedo auto-restart --patterns=*.py --recursive -- 
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload
  db_mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data: