# 1º Paso: Usar una imagen base oficial de Python
FROM python:3.9

# 2º Paso: Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# 3º Paso: Copiar los archivos de requisitos primero para aprovechar la caché de Docker
COPY requirements.txt .

# 4º Paso: Instalar las dependencias del proyecto
RUN pip install --no-cache-dir -r requirements.txt

# 5º Paso: Copiar el resto del código de la aplicación al directorio de trabajo
COPY . .

# 6º Paso:Exponer el puerto en el que la aplicación estará escuchando
EXPOSE 8000

# 7º Paso:Comando para ejecutar la aplicación usando uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]