version: "3.9"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    links:
      - db_mongo
  db_mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234